**jumbo rolls are folded in**

**changeover between jumbos are folded in**

need to add 'pulled from inventory' rows to the schedule.

or maybe show when an order in the future has been fullfilled.

then optimize for knife changes

# Simple Genetic Algorithm to Optimize Deckle Loss

In [2]:
import sys
sys.path.append("../")

In [3]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import math
from random import shuffle, choice
import copy
from utils import *
from genetic import *
from IPython.display import clear_output
import time
import datetime
import re

In [5]:
df = pd.read_excel('../data/200721_ New Way SCH W3-W6 W14 07.20.20.xlsx',
                   sheet_name='Schedule')

df_input_schedule = pd.read_excel('../data/200721_ New Way SCH W3-W6 W14 07.20.20.xlsx',
                   sheet_name='Schedule')
df_input_schedule.insert(1, 'Technology', df_input_schedule['Description'].apply(lambda x: parse_description(x, 'tech')))
df_input_schedule.insert(2, 'Color', df_input_schedule['Description'].apply(lambda x: x.split(';')[1] if type(x) == str else None))
df_input_schedule.insert(3, 'Width', df_input_schedule['Description'].apply(lambda x: parse_description(x, 'width')))
df_input_schedule = df_input_schedule[[col for col in df_input_schedule.columns if 'Unnamed' not in str(col)]]
temp = df_input_schedule[['Customer Name', 'Technology', 'Color', 'Width', 'CYCLE / BUCKET',
                          'Description', 'Total LM Order QTY',
                          'Scheduled Ship Date', 'Date order is complete']]

In [6]:
temp

,Customer Name,Technology,Color,Width,CYCLE / BUCKET,Description,Total LM Order QTY,Scheduled Ship Date,Date order is complete
0,P & G,SAM,WHITE,208,CYCLE 1,SAM0130UN0208;WHITE;300,3.698225e+05,2020-07-21 00:00:00,2020-07-20 13:05:05.263
1,P & G,SAM,WHITE,170,CYCLE 1,SAM0130UN0170;WHITE;300,2.262443e+06,2020-07-21 00:00:00,2020-07-20 16:00:31.579
2,P & G,SAM,WHITE,234,CYCLE 1,SAM0130UN0234;WHITE;300,2.005260e+06,2020-07-22 00:00:00,2020-07-20 19:34:33.684
3,P & G,SAM,WHITE,234,CYCLE 1,SAM0130UN0234;WHITE;300,2.136752e+06,2020-07-22 00:00:00,2020-07-20 23:22:37.895
4,P & G,SAM,WHITE,234,CYCLE 1,SAM0130UN0234;WHITE;300,2.136752e+06,2020-07-22 00:00:00,2020-07-21 03:10:42.105
...,...,...,...,...,...,...,...,...,...
355,CARDINAL HEALTH,SM,WHITE,575,CYCLE 6,SM10120UN0575;WHITE;300,1.898551e+07,FC,2020-12-25 14:58:21.064
356,NaN,None,None,None,CYCLE 6,NaN,NaN,CHANGE OVER,2020-12-25 15:28:21.064
357,P & G,SM,WHITE,080,CYCLE 6,SM30330UN0080;WHITE;600,2.803030e+07,FC,2020-12-27 20:40:17.958
358,IRVING CONSUMER PRODUCTS,SM,WHITE,080,CYCLE 6,SM30330UN0080;WHITE;600,7.575758e+06,FC,2020-12-28 11:02:59.281
359,Allotted trial time,None,None,None,CYCLE 6,NaN,NaN,trials,2020-12-28 23:02:59.281

In [302]:
# temp = temp[temp['Scheduled Ship Date'].apply(lambda x: type(x) == int)]                          
temp_json = temp.to_json()

In [305]:
temp2

,Customer Name,Technology,Color,Width,CYCLE / BUCKET,Description,Total LM Order QTY,Scheduled Ship Date,Date order is complete
0,P & G,SAM,WHITE,208.0,CYCLE 1,SAM0130UN0208;WHITE;300,3.698225e+05,1595289600000,2020-07-20 13:05:05.263
1,P & G,SAM,WHITE,170.0,CYCLE 1,SAM0130UN0170;WHITE;300,2.262443e+06,1595289600000,2020-07-20 16:00:31.579
2,P & G,SAM,WHITE,234.0,CYCLE 1,SAM0130UN0234;WHITE;300,2.005260e+06,1595376000000,2020-07-20 19:34:33.684
3,P & G,SAM,WHITE,234.0,CYCLE 1,SAM0130UN0234;WHITE;300,2.136752e+06,1595376000000,2020-07-20 23:22:37.895
4,P & G,SAM,WHITE,234.0,CYCLE 1,SAM0130UN0234;WHITE;300,2.136752e+06,1595376000000,2020-07-21 03:10:42.105
...,...,...,...,...,...,...,...,...,...
355,CARDINAL HEALTH,SM,WHITE,575.0,CYCLE 6,SM10120UN0575;WHITE;300,1.898551e+07,FC,2020-12-25 14:58:21.064
356,None,None,None,NaN,CYCLE 6,None,NaN,CHANGE OVER,2020-12-25 15:28:21.064
357,P & G,SM,WHITE,80.0,CYCLE 6,SM30330UN0080;WHITE;600,2.803030e+07,FC,2020-12-27 20:40:17.958
358,IRVING CONSUMER PRODUCTS,SM,WHITE,80.0,CYCLE 6,SM30330UN0080;WHITE;600,7.575758e+06,FC,2020-12-28 11:02:59.281
359,Allotted trial time,None,None,NaN,CYCLE 6,None,NaN,trials,2020-12-28 23:02:59.281

In [311]:
temp2 = pd.read_json(temp_json, convert_dates=['Scheduled Ship Date', 'Date order is complete'])
# temp2[temp2['Scheduled Ship Date'].apply(lambda x: type(x) == int)]
# temp[temp['Scheduled Ship Date'].apply(lambda x: datetime.datetime(x))]
temp2['Scheduled Ship Date'] = pd.to_datetime(temp2['Scheduled Ship Date'], errors='ignore', unit='ms')
temp2

,Customer Name,Technology,Color,Width,CYCLE / BUCKET,Description,Total LM Order QTY,Scheduled Ship Date,Date order is complete
0,P & G,SAM,WHITE,208.0,CYCLE 1,SAM0130UN0208;WHITE;300,3.698225e+05,2020-07-21 00:00:00,2020-07-20 13:05:05.263
1,P & G,SAM,WHITE,170.0,CYCLE 1,SAM0130UN0170;WHITE;300,2.262443e+06,2020-07-21 00:00:00,2020-07-20 16:00:31.579
2,P & G,SAM,WHITE,234.0,CYCLE 1,SAM0130UN0234;WHITE;300,2.005260e+06,2020-07-22 00:00:00,2020-07-20 19:34:33.684
3,P & G,SAM,WHITE,234.0,CYCLE 1,SAM0130UN0234;WHITE;300,2.136752e+06,2020-07-22 00:00:00,2020-07-20 23:22:37.895
4,P & G,SAM,WHITE,234.0,CYCLE 1,SAM0130UN0234;WHITE;300,2.136752e+06,2020-07-22 00:00:00,2020-07-21 03:10:42.105
...,...,...,...,...,...,...,...,...,...
355,CARDINAL HEALTH,SM,WHITE,575.0,CYCLE 6,SM10120UN0575;WHITE;300,1.898551e+07,FC,2020-12-25 14:58:21.064
356,None,None,None,NaN,CYCLE 6,None,NaN,CHANGE OVER,2020-12-25 15:28:21.064
357,P & G,SM,WHITE,80.0,CYCLE 6,SM30330UN0080;WHITE;600,2.803030e+07,FC,2020-12-27 20:40:17.958
358,IRVING CONSUMER PRODUCTS,SM,WHITE,80.0,CYCLE 6,SM30330UN0080;WHITE;600,7.575758e+06,FC,2020-12-28 11:02:59.281
359,Allotted trial time,None,None,NaN,CYCLE 6,None,NaN,trials,2020-12-28 23:02:59.281

In [287]:
datetime.datetime?

In [230]:
df.insert(1, 'Technology', df['Description'].apply(lambda x: parse_description(x, 'tech')))
df.insert(2, 'Color', df['Description'].apply(lambda x: x.split(';')[1] if type(x) == str else None))
df.insert(3, 'Width', df['Description'].apply(lambda x: parse_description(x, 'width')))
df = df[[col for col in df.columns if 'Unnamed' not in str(col)]]

In [135]:
customer_names = [i for i in df['Customer Name'].unique() if type(i) == str]
print(customer_names)

['P & G', 'FIRST QUALITY PRODUCTS', 'PRECEPT MEDICAL', 'CARDINAL HEALTH', 'AHP', 'IRVING CONSUMER PRODUCTS', 'GRIFFIN CARE', 'CHANGE OVER', 'FIRST QUALITY RETAIL SERVICE', 'IRVING PERSONAL CARE', 'Allotted trial time', 'ARIUM CHANGE OVER']

In [215]:
def parse_description(text, grab='tech'):
    '''
    returns technology type from schedule description
    '''
    if type(text) == str:
        match = re.match(r"([a-z]+)([0-9]+)([a-z]+0)([0-9]+)", text, re.I)
        if match:
            if grab == 'tech':
                return match.groups()[0] # first value is the technology
            elif grab == 'width':
                return match.groups()[-1] # last value is the width

In [238]:
df.columns

Index(['SPM375014                               PROD. DATE',
                                               'Technology',
                                                    'Color',
                                                    'Width',
                                           'CYCLE / BUCKET',
                                            'Customer Name',
                                                  'Item No',
                                                      'WO#',
                                              'Description',
                                                'Treatment',
                                                       'KG',
                                         'Hours To Produce',
                                                  'Polymer',
                                                'Core Size',
                                                 'LM putup',
                                            'Roll Diameter',
                                         'Rolls per Bundle',
                                        'Packaging Top/Bot',
                                               '# OF ROLLS',
                                       'Total LM Order QTY',
                                      'Scheduled Ship Date',
                                            'Sales Order #',
                                   'Date order is complete',
                                        2020-07-20 12:30:00,
                                                '% reclaim',
                                      'Amount Repro needed',
                                            'Type of Repro'],
      dtype='object')

In [212]:
match = re.match(r"([a-z]+)([0-9]+)([a-z]+0)([0-9]+)", text, re.I)
match.groups()

('SAM', '0130', 'UN0', '234')

In [185]:
text.split(';')

['SAM0130UN0208', 'WHITE', '300']

In [129]:
technologies = list(set([grab_technology(i) for i in df['Description'] 
                         if (type(i) == str)]))
technologies = [i for i in technologies if i]
print(technologies)

['SA', 'SM', 'SAM']

In [131]:
colors = list(set([i[1] for i in list(df['Description']
                .str.split(';')) if type(i) == list]))
print(colors)

['KCBLUE', 'DENBLU2', 'CYAN ', 'TEAL2ARI', 'WHITE', 'PURPLE', 'DKPINK', 'PINK', 'DENBLUE', 'SEAFOAM', 'PURP']

In [133]:
cycles = list(df['CYCLE / BUCKET'].unique())
print(cycles)

['CYCLE 1', 'CYCLE 2', 'CYCLE 3', 'CYCLE 4', 'CYCLE 5', 'CYCLE 6']

In [141]:
customer = 'P & G'
technology = 'SAM' # Technology -> 
color = 'WHITE'
cycle = 'CYCLE 2'

df_filtered = df.loc[df['Customer Name'] == customer]
df_filtered = df_filtered.loc[df_filtered['Description'].str.contains(technology)]
df_filtered = df_filtered.loc[df_filtered['Description'].str.contains(color)] #CYAN, TEAL
df_filtered = df_filtered.loc[df_filtered['CYCLE / BUCKET'] == cycle]
df_filtered.insert(0, 'Block', 1)

### if index is broken, create new block

In [158]:
prev_index = df_filtered.index[0] - 1
block = 1
for index in df_filtered.index:
    if index != prev_index + 1:
        block += 1
    df_filtered.loc[index, 'Block'] = block
    prev_index = index

In [240]:
customer = 'P & G'
product = 'SAM' # Technology -> 
color = 'WHITE'
cycle = 'CYCLE 2'

df = pd.read_excel('../../data/berry/200721_ New Way SCH W3-W6 W14 07.20.20.xlsx',
                   sheet_name='Schedule')
df = df.loc[df['Customer Name'] == customer]
df = df.loc[df['Description'].str.contains(product)]
df = df.loc[df['Description'].str.contains(color)] #CYAN, TEAL
df = df.loc[df['CYCLE / BUCKET'] == cycle]
df = df.reset_index(drop=True)
df['Width'] = pd.DataFrame(list(pd.DataFrame(list(df['Description'].str.split(';')))[0].str.split('UN0')))[1]
lm = list(df.groupby('Description')['Total LM Order QTY'].sum().values)
widths = list(df.groupby('Description')['Width'].first().values.astype(int))
doffs_in_jumbo = 6
B = 4160
L = doff_length = 17000 * doffs_in_jumbo # df['LM putup']

neckin = [4, 4, 5, 7, 7, 7] # 158 missing in cycle 1, 4 mm knife in
w = list(np.array(widths) + np.array(neckin))
q = [math.ceil(x/L) for x in lm]
print("max doffs needed without stock cutting: {}".format(q))
s = BinPackingExample(w, q)
df_json = df.to_json()

max doffs needed without stock cutting: [96, 32, 318, 95, 158, 461]

In [257]:
(df.iloc[:4].groupby('Width')['Total LM Order QTY'].sum().index.values.astype(int))

array([154, 170])

[('SAM0130UN0154;WHITE;300', 2    154
  Name: Width, dtype: object), ('SAM0130UN0170;WHITE;300', 0    170
  1    170
  3    170
  Name: Width, dtype: object)]

In [250]:
df.iloc[:4][['Description', 'Total LM Order QTY']]

               Description  Total LM Order QTY
0  SAM0130UN0170;WHITE;300        2.941176e+06
1  SAM0130UN0170;WHITE;300        2.941176e+06
2  SAM0130UN0154;WHITE;300        3.246753e+06
3  SAM0130UN0170;WHITE;300        2.941176e+06

In [ ]:
neckins = []
for width in widths:
    if width < 170:
        neckin = 4
    elif width < 208:
        neckin = 5
    else: 
        neckin = 7
    neckins.append(neckin)

In [3]:
# B = 3850-200 # useful Doff width in MM (RW-Trim)
# L = 22500 # put up, Doff length
# w = widths = [531+8,667+11,574+10] # roll widths with Neck In
# lm = [1035000, 945000, 958188] # material needed in LM
# q = [math.ceil(x/L) for x in lm]
# print("max doffs needed without stock cutting: {}".format(q))

if we gave each order its own entire row we would produce a lot of wasted material

# Run Deckle Optimizer

In [4]:
sol, loss = find_optimum(s, B, widths, neckin, max_unique_products=4, loss_target=2)

gene time: 0.4, chromosome time: 1598556646.6, ffd time: 0.4
loss: 0.962, best loss: 0.962, steps: 2, gene count: 5, unique doffs: 11, max unique on doff: 4
                          Formula Doffs  Loss
0          170x6 + 218x2 + 234x11    24     9
1   154x2 + 170x7 + 218x2 + 234x9    21     0
2                          208x19     4    75
3                          218x18     3   110
4                          154x20     1  1000
5                          154x26     1    52
6                  154x8 + 158x17     1   142
7                  158x15 + 170x9     1   155
8                  170x17 + 208x5     1   110
9                  208x14 + 218x5     1    25
10          170x1 + 218x9 + 234x8     1    32

# Build Layout for Dashboard View

In [5]:
layout_summary(sol, widths, neckin, B)

,0,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,Doffs,Loss
Doffs,,,,,,,,,,,,,,,,,,,,,
1,154.0,154.0,154.0,154.0,154.0,154.0,154.0,154.0,154.0,154.0,...,154.0,154.0,NaN,NaN,NaN,NaN,NaN,NaN,1,1000.0
1,154.0,154.0,154.0,154.0,154.0,154.0,154.0,154.0,154.0,154.0,...,154.0,154.0,154.0,154.0,154.0,154.0,154.0,154.0,1,52.0
1,158.0,158.0,158.0,158.0,158.0,158.0,158.0,158.0,158.0,158.0,...,154.0,154.0,154.0,154.0,154.0,154.0,154.0,NaN,1,142.0
1,170.0,170.0,170.0,170.0,170.0,170.0,170.0,170.0,170.0,158.0,...,158.0,158.0,158.0,158.0,158.0,158.0,NaN,NaN,1,155.0
21,170.0,170.0,218.0,234.0,154.0,170.0,234.0,234.0,218.0,170.0,...,234.0,170.0,NaN,NaN,NaN,NaN,NaN,NaN,21,0.0
1,208.0,208.0,208.0,208.0,208.0,170.0,170.0,170.0,170.0,170.0,...,170.0,170.0,170.0,170.0,NaN,NaN,NaN,NaN,1,110.0
4,208.0,208.0,208.0,208.0,208.0,208.0,208.0,208.0,208.0,208.0,...,208.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,75.0
1,218.0,218.0,218.0,218.0,218.0,208.0,208.0,208.0,208.0,208.0,...,208.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,25.0
3,218.0,218.0,218.0,218.0,218.0,218.0,218.0,218.0,218.0,218.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,110.0
24,234.0,234.0,234.0,234.0,234.0,234.0,234.0,170.0,218.0,234.0,...,170.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24,9.0
1,234.0,234.0,234.0,234.0,234.0,234.0,234.0,234.0,218.0,218.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,32.0

# Run Master Schedule, Optimizing Late Orders

In [6]:
optimize_late_orders(sol, widths, neckin, df, L, set_readable=True)

   154  158  170  208  218  234
0  0.0  NaN -1.0 -1.0 -3.0 -1.0

                          Formula Doffs
0                  170x17 + 208x5     1
1                  158x15 + 170x9     1
2   154x2 + 170x7 + 218x2 + 234x9     1
3   154x2 + 170x7 + 218x2 + 234x9     4
4                          154x26     1
5   154x2 + 170x7 + 218x2 + 234x9     4
6   154x2 + 170x7 + 218x2 + 234x9     4
7                          218x18     3
8          170x6 + 218x2 + 234x11     1
9                  154x8 + 158x17     1
10         170x6 + 218x2 + 234x11    23
11  154x2 + 170x7 + 218x2 + 234x9     8
12          170x1 + 218x9 + 234x8     1
13                 208x14 + 218x5     1
14                         154x20     1
15                         208x19     4

In [7]:
# run through schedule
# first roll
# change knife, jumbo, and manderal
# run at slitter speed
# look at next roll
# if same knife setup only change jumbo setup
# otherwise change jumbo + knife 
# loop

In [8]:
extras = pd.DataFrame(np.zeros(len(widths))).T
master2 = make_layout_registrar(sol, widths, neckin)
extras.columns = master2.columns[:-1]
schedule = []
schedule_with_order_info = []
layout_pattern = 0
old_width = width = None
completed_orders = []

#### logic for jumbo rolls should go in first loop
for row1 in df.index:
    clear_output(wait=True)
    ### select schedule data
    current_scheduled = df.iloc[row1][['Total LM Order QTY', 'Width', 'Scheduled Ship Date']]
    current_scheduled['Order Number'] = row1+1
    ship_date = current_scheduled['Scheduled Ship Date']
    doffs = math.ceil(current_scheduled['Total LM Order QTY'] / L) # QTY
    width = current_scheduled['Width']
    
    ### check if we've entered a new product
    ### no setup changes here, we need to see if the layout has changed
    if width == old_width:
        layout_pattern -= 1
        
    ### sort by the current scheduled width in master 2
    master2 = master2.sort_values(width, ascending=False).reset_index(drop=True)
    
    ### calc how many new doffs need to be made from inventory
    target_doffs = extras.iloc[0][width]
    print(pd.DataFrame(data=[[doffs, width, target_doffs]], 
                       columns=['required doffs', 'width', 'doffs made']))
    print(doffs, width, target_doffs)
    
    ### only proceed if doffs are available in layout registrar
    ### and not in inventory 
    if ((any(master2.loc[master2[width] > 0]['freq'] > 0)) 
        and (target_doffs <= doffs)): 
    
    ### go through the rows in the master2 registrar and check for
    ### layout patterns that contain our current width
    
    ### Every row is a new layout unless the outer 
    ### loop has incremented, then only maybe is it
    ### a new layout
        for row in master2.index: 
            
            # if none of the width are in the layout then break out
            if np.isnan(master2.iloc[row][width]): 
                break
            layout_pattern += 1
            
            # looping through available doffs in the layout
            for count in range(master2.iloc[row]['freq'].astype(int)): 
                
                # add to target doffs
                target_doffs += master2.iloc[row][width] 
                
                # add to number of times we've made this layout
                master2.at[row, 'layout number'] = layout_pattern 
                
              
                new_layout_and_scheduled_product = pd.concat([master2.iloc[row], 
                                                              current_scheduled])
                schedule_with_order_info.append(new_layout_and_scheduled_product)
                schedule.append(master2.iloc[row])
                master2.at[row, 'freq'] = master2.at[row, 'freq'] - 1

                ### Tabluate the other widths that were made on the layout
                for master_index in master2.iloc[row].index[:-2]:
                    if (math.isnan(master2.iloc[row][master_index]) == False):
                        ### tabulate extras for other widths in the layout
                        extras.iloc[0][master_index] = extras.iloc[0][master_index] +\
                            master2.iloc[row][master_index]
                        completed_orders.append
                if target_doffs >= doffs:
                    
                    ### add to registrar of completed orders.
                    completed_orders.append(current_scheduled['Order Number'])
                    
                    ### now that we've finished this order, we want to see if we've completed any other orders as well
                    
                    
                    break
            ### for exiting nested for loop
            else:
                continue
            break
    old_width = width
    extra = target_doffs - doffs
    extras.iloc[0][width] = extra
    
    print(extras)
    
sorted_schedule_with_order_info = pd.DataFrame(schedule_with_order_info)
sorted_schedule_with_order_info = sorted_schedule_with_order_info.reset_index(drop=True)
sorted_schedule = pd.DataFrame(schedule)
sorted_schedule = sorted_schedule.reset_index(drop=True)

   required doffs width  doffs made
0              21   234        20.0
21 234 20.0
   154  158  170  208  218  234
0  0.0  0.0 -1.0 -1.0 -3.0 -1.0

In [9]:
completed_orders

[1, 2, 3, 4, 5, 7, 8, 10, 11, 12, 13, 14, 18, 22, 23, 35, 37, 40]

In [10]:
sorted_schedule_with_order_info

,154,158,170,208,218,234,freq,layout number,Total LM Order QTY,Width,Scheduled Ship Date,Order Number
0,NaN,NaN,17.0,5.0,NaN,NaN,1.0,1.0,2.941176e+06,170,2020-08-05,1
1,NaN,15.0,9.0,NaN,NaN,NaN,1.0,2.0,2.941176e+06,170,2020-08-05,1
2,2.0,NaN,7.0,NaN,2.0,9.0,21.0,3.0,2.941176e+06,170,2020-08-05,1
3,2.0,NaN,7.0,NaN,2.0,9.0,20.0,5.0,2.941176e+06,170,2020-08-06,2
4,2.0,NaN,7.0,NaN,2.0,9.0,19.0,5.0,2.941176e+06,170,2020-08-06,2
5,2.0,NaN,7.0,NaN,2.0,9.0,18.0,5.0,2.941176e+06,170,2020-08-06,2
6,2.0,NaN,7.0,NaN,2.0,9.0,17.0,5.0,2.941176e+06,170,2020-08-06,2
7,26.0,NaN,NaN,NaN,NaN,NaN,1.0,6.0,3.246753e+06,154,2020-08-07,3
8,2.0,NaN,7.0,NaN,2.0,9.0,16.0,9.0,2.941176e+06,170,2020-08-07,4
9,2.0,NaN,7.0,NaN,2.0,9.0,15.0,9.0,2.941176e+06,170,2020-08-07,4
10,2.0,NaN,7.0,NaN,2.0,9.0,14.0,9.0,2.941176e+06,170,2020-08-07,4
11,2.0,NaN,7.0,NaN,2.0,9.0,13.0,9.0,2.941176e+06,170,2020-08-07,4
12,2.0,NaN,7.0,NaN,2.0,9.0,12.0,11.0,2.941176e+06,170,2020-08-07,5
13,2.0,NaN,7.0,NaN,2.0,9.0,11.0,11.0,2.941176e+06,170,2020-08-07,5
14,2.0,NaN,7.0,NaN,2.0,9.0,10.0,11.0,2.941176e+06,170,2020-08-07,5
15,2.0,NaN,7.0,NaN,2.0,9.0,9.0,11.0,2.941176e+06,170,2020-08-07,5
16,NaN,NaN,NaN,NaN,18.0,NaN,3.0,11.0,2.293578e+06,218,2020-08-07,7
17,NaN,NaN,NaN,NaN,18.0,NaN,2.0,11.0,2.293578e+06,218,2020-08-07,7
18,NaN,NaN,NaN,NaN,18.0,NaN,1.0,11.0,2.293578e+06,218,2020-08-07,8
19,8.0,17.0,NaN,NaN,NaN,NaN,1.0,12.0,3.164557e+06,158,2020-08-13,10
20,2.0,NaN,7.0,NaN,2.0,9.0,8.0,15.0,2.941176e+06,170,2020-08-14,11
21,2.0,NaN,7.0,NaN,2.0,9.0,7.0,15.0,2.941176e+06,170,2020-08-14,11
22,2.0,NaN,7.0,NaN,2.0,9.0,6.0,15.0,2.941176e+06,170,2020-08-14,11
23,2.0,NaN,7.0,NaN,2.0,9.0,5.0,15.0,2.941176e+06,170,2020-08-14,11
24,NaN,NaN,NaN,19.0,NaN,NaN,4.0,16.0,2.403846e+06,208,2020-08-14,12
25,NaN,NaN,NaN,19.0,NaN,NaN,3.0,16.0,2.403846e+06,208,2020-08-14,13
26,NaN,NaN,NaN,19.0,NaN,NaN,2.0,16.0,2.403846e+06,208,2020-08-14,13
27,NaN,NaN,1.0,NaN,9.0,8.0,1.0,18.0,2.293578e+06,218,2020-08-14,14
28,NaN,NaN,NaN,14.0,5.0,NaN,1.0,19.0,2.293578e+06,218,2020-08-17,18
29,NaN,NaN,6.0,NaN,2.0,11.0,24.0,20.0,2.293578e+06,218,2020-08-17,18
30,NaN,NaN,6.0,NaN,2.0,11.0,23.0,20.0,2.293578e+06,218,2020-08-17,18
31,NaN,NaN,6.0,NaN,2.0,11.0,22.0,20.0,2.293578e+06,218,2020-08-17,18
32,NaN,NaN,6.0,NaN,2.0,11.0,21.0,20.0,2.293578e+06,218,2020-08-17,18
33,NaN,NaN,6.0,NaN,2.0,11.0,20.0,20.0,2.293578e+06,218,2020-08-17,18
34,NaN,NaN,6.0,NaN,2.0,11.0,19.0,20.0,2.293578e+06,218,2020-08-17,18
35,NaN,NaN,6.0,NaN,2.0,11.0,18.0,20.0,2.293578e+06,218,2020-08-17,18
36,2.0,NaN,7.0,NaN,2.0,9.0,4.0,22.0,2.941176e+06,170,2020-08-19,22
37,2.0,NaN,7.0,NaN,2.0,9.0,3.0,22.0,2.941176e+06,170,2020-08-19,22
38,2.0,NaN,7.0,NaN,2.0,9.0,2.0,22.0,2.941176e+06,170,2020-08-19,22
39,2.0,NaN,7.0,NaN,2.0,9.0,1.0,26.0,2.293578e+06,218,2020-08-19,23
40,NaN,NaN,6.0,NaN,2.0,11.0,17.0,27.0,2.293578e+06,218,2020-08-19,23
41,NaN,NaN,6.0,NaN,2.0,11.0,16.0,27.0,2.293578e+06,218,2020-08-19,23
42,NaN,NaN,6.0,NaN,2.0,11.0,15.0,27.0,2.293578e+06,218,2020-08-19,23
43,NaN,NaN,6.0,NaN,2.0,11.0,14.0,27.0,2.293578e+06,218,2020-08-19,23
44,NaN,NaN,6.0,NaN,2.0,11.0,13.0,27.0,2.293578e+06,218,2020-08-19,23
45,NaN,NaN,6.0,NaN,2.0,11.0,12.0,27.0,2.293578e+06,218,2020-08-19,23
46,NaN,NaN,6.0,NaN,2.0,11.0,11.0,27.0,2.293578e+06,218,2020-08-19,23
47,NaN,NaN,6.0,NaN,2.0,11.0,10.0,19.0,2.136752e+06,234,2020-08-24,35
48,NaN,NaN,6.0,NaN,2.0,11.0,9.0,22.0,2.941176e+06,170,2020-08-25,37
49,NaN,NaN,6.0,NaN,2.0,11.0,8.0,22.0,2.941176e+06,170,2020-08-25,37
50,NaN,NaN,6.0,NaN,2.0,11.0,7.0,22.0,2.941176e+06,170,2020-08-25,37
51,NaN,NaN,6.0,NaN,2.0,11.0,6.0,22.0,2.941176e+06,170,2020-08-25,37
52,NaN,NaN,6.0,NaN,2.0,11.0,5.0,22.0,2.941176e+06,170,2020-08-25,37
53,NaN,NaN,6.0,NaN,2.0,11.0,4.0,27.0,2.293578e+06,218,2020-08-26,39
54,NaN,NaN,6.0,NaN,2.0,11.0,3.0,27.0,2.293578e+06,218,2020-08-26,39
55,NaN,NaN,6.0,NaN,2.0,11.0,2.0,27.0,2.293578e+06,218,2020-08-26,39
56,NaN,NaN,6.0,NaN,2.0,11.0,1.0,27.0,2.293578e+06,218,2020-08-26,39
57,20.0,NaN,NaN,NaN,NaN,NaN,1.0,29.0,3.246753e+06,154,2020-08-27,40
58,NaN,NaN,NaN,19.0,NaN,NaN,1.0,28.0,2.403846e+06,208,2020-08-28,45

In [11]:
setup_df = pd.read_excel('../../data/berry/200725_WAVA Deckle Optimization Parameters Rev1.xlsx', sheet_name='Deckle Parameters')
speed_df = pd.read_excel('../../data/berry/200725_WAVA Deckle Optimization Parameters Rev1.xlsx', sheet_name='Product Parameters')

In [12]:
setup_df

,Slitter Set-up,Time (minutes),Unnamed: 2
0,AMB & Arium,50,arium is a product. Sounds like this happens b...
1,Normal Knife,15,NaN
2,Knife and Manderel,30,NaN
3,<100mm slits,30,NaN
4,Jumbo Roll Set-up,Time (minutes),NaN
5,Jumbo roll only,15,NaN
6,Jumbo roll and knife,30,NaN
7,Jumbo roll and knife and manderal,30,NaN
8,Jumbo roll and <100mm slits,45,NaN
9,Slit Off-set definitiaon,Target width + Slit Off-set,NaN
10,Slit Combinations,# of slit widths,NaN
11,# of slit combinations - preferred,3,NaN
12,Max # slit combinations,4,NaN
13,"Abiltiy to run 2,3 or 4 combinations",(wrapper bottle-neck),NaN
14,Slit Off-set definitiaon,Target width + Slit Off-set,NaN

In [13]:
slitter_speed = speed_df.loc[(speed_df['Customer Name'] == customer) &
             (speed_df['Description'].str.contains(technology)) &
             (speed_df['Description'].str.contains(color)), 'Slittter Speed (m/min)'].reset_index(drop=True)[0]
slitter_speed

1300

In [14]:
# add column 'completion date/time'
# for row in schedule, calculate the completion time
sorted_schedule_with_order_info['Completion Date'] = None

### choose starte date/time
start_date_time = datetime.datetime(2020, 8, 12)
print("start time: {}".format(start_date_time))

### set changeover times
jumbo_change = setup_df.loc[setup_df['Slitter Set-up'] == 
                            'Jumbo roll only']['Time (minutes)'].values[0]
jumbo_change = datetime.timedelta(minutes=jumbo_change)
print("jumbo change: {}".format(jumbo_change))
jumbo_and_knife_change = setup_df.loc[setup_df['Slitter Set-up'] == 
                                      'AMB & Arium']['Time (minutes)'].values[0]
jumbo_and_knife_change = datetime.timedelta(minutes=jumbo_and_knife_change)
print("jumbo and knife change: {}".format(jumbo_and_knife_change))

### print slitter speed and doff length
print("slitter speed (m/min): {}".format(slitter_speed))
print("doff length (m): {}".format(doff_length))
prior_completion_date_time = start_date_time
match = '\d\d\d'
layout_columns = [i for i in sorted_schedule_with_order_info.columns if re.match(match, i)]

### zero-out the 'prior layout' so algorithm knows jumbo + knife change
prior_layout = sorted_schedule_with_order_info.iloc[0][layout_columns]
for col in prior_layout.index:
    prior_layout[col] = 0
layout_number = 0

schedule_with_change_over = pd.DataFrame()
### transition times are for loading the current jumbo
for row in sorted_schedule_with_order_info.index:
    
    layout = sorted_schedule_with_order_info.iloc[row][layout_columns]
    if all(prior_layout.fillna(0) == layout.fillna(0)):
        transition_time = jumbo_change
    else:
        transition_time = jumbo_and_knife_change
        layout_number += 1
    print("transition time: {}".format(transition_time))
    run_time = doff_length / slitter_speed
    run_time = datetime.timedelta(minutes=run_time)
    print("run time: {}".format(run_time))
    completion_time = transition_time + run_time
    completion_date_time = prior_completion_date_time + completion_time
    print("completion date/time: {}".format(completion_date_time))
    
    ### change main df
    sorted_schedule_with_order_info['Completion Date'][row] = completion_date_time
    sorted_schedule_with_order_info['layout number'][row] = layout_number
    
    ### with changeover rows
    current_changeover = pd.DataFrame(sorted_schedule_with_order_info.columns)
    current_changeover = current_changeover.set_index(0)
    current_changeover = current_changeover.T
    current_changeover = current_changeover.append({'Order Number': 'Changeover'}, ignore_index=True)
    current_changeover['Completion Date'] = prior_completion_date_time + transition_time
    current_order = pd.DataFrame(sorted_schedule_with_order_info.iloc[row]).T
    current_combined = current_changeover.append(current_order, sort=False, ignore_index=True)
    
    schedule_with_change_over = pd.concat([schedule_with_change_over, current_combined])
    
    prior_completion_date_time = completion_date_time
    prior_layout = layout
    clear_output(wait=True)

transition time: 0:50:00
run time: 1:18:27.692308
completion date/time: 2020-08-16 05:14:13.846172

In [15]:
schedule_with_change_over = schedule_with_change_over.reset_index(drop=True)

In [16]:
schedule_with_change_over.head(40)

,154,158,170,208,218,234,freq,layout number,Total LM Order QTY,Width,Scheduled Ship Date,Order Number,Completion Date
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 00:50:00.000000
1,NaN,NaN,17,5,NaN,NaN,1,1,2.94118e+06,170,2020-08-05,1,2020-08-12 02:08:27.692308
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 02:58:27.692308
3,NaN,15,9,NaN,NaN,NaN,1,2,2.94118e+06,170,2020-08-05,1,2020-08-12 04:16:55.384616
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 05:06:55.384616
5,2,NaN,7,NaN,2,9,21,3,2.94118e+06,170,2020-08-05,1,2020-08-12 06:25:23.076924
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 06:40:23.076924
7,2,NaN,7,NaN,2,9,20,3,2.94118e+06,170,2020-08-06,2,2020-08-12 07:58:50.769232
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 08:13:50.769232
9,2,NaN,7,NaN,2,9,19,3,2.94118e+06,170,2020-08-06,2,2020-08-12 09:32:18.461540
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 09:47:18.461540
11,2,NaN,7,NaN,2,9,18,3,2.94118e+06,170,2020-08-06,2,2020-08-12 11:05:46.153848
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 11:20:46.153848
13,2,NaN,7,NaN,2,9,17,3,2.94118e+06,170,2020-08-06,2,2020-08-12 12:39:13.846156
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 13:29:13.846156
15,26,NaN,NaN,NaN,NaN,NaN,1,4,3.24675e+06,154,2020-08-07,3,2020-08-12 14:47:41.538464
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 15:37:41.538464
17,2,NaN,7,NaN,2,9,16,5,2.94118e+06,170,2020-08-07,4,2020-08-12 16:56:09.230772
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 17:11:09.230772
19,2,NaN,7,NaN,2,9,15,5,2.94118e+06,170,2020-08-07,4,2020-08-12 18:29:36.923080
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 18:44:36.923080
21,2,NaN,7,NaN,2,9,14,5,2.94118e+06,170,2020-08-07,4,2020-08-12 20:03:04.615388
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 20:18:04.615388
23,2,NaN,7,NaN,2,9,13,5,2.94118e+06,170,2020-08-07,4,2020-08-12 21:36:32.307696
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 21:51:32.307696
25,2,NaN,7,NaN,2,9,12,5,2.94118e+06,170,2020-08-07,5,2020-08-12 23:10:00.000004
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 23:25:00.000004
27,2,NaN,7,NaN,2,9,11,5,2.94118e+06,170,2020-08-07,5,2020-08-13 00:43:27.692312
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 00:58:27.692312
29,2,NaN,7,NaN,2,9,10,5,2.94118e+06,170,2020-08-07,5,2020-08-13 02:16:55.384620
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 02:31:55.384620
31,2,NaN,7,NaN,2,9,9,5,2.94118e+06,170,2020-08-07,5,2020-08-13 03:50:23.076928
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 04:40:23.076928
33,NaN,NaN,NaN,NaN,18,NaN,3,6,2.29358e+06,218,2020-08-07,7,2020-08-13 05:58:50.769236
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 06:13:50.769236
35,NaN,NaN,NaN,NaN,18,NaN,2,6,2.29358e+06,218,2020-08-07,7,2020-08-13 07:32:18.461544
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 07:47:18.461544
37,NaN,NaN,NaN,NaN,18,NaN,1,6,2.29358e+06,218,2020-08-07,8,2020-08-13 09:05:46.153852
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 09:55:46.153852
39,8,17,NaN,NaN,NaN,NaN,1,7,3.16456e+06,158,2020-08-13,10,2020-08-13 11:14:13.846160

In [17]:
# summary w changeover rows

master_schedule = pd.DataFrame()
unformatted_schedule = pd.DataFrame()
for index in schedule_with_change_over.index[1::2]: # pass through every jumbo
    order_number = schedule_with_change_over.iloc[index]['Order Number']
    
    ### these are columns specific to width layouts
    match = '\d\d\d'
    layout_columns = [i for i in schedule_with_change_over.columns if re.match(match, i)]
    
    
    deckle_layout =  deckle_order = pd.DataFrame(schedule_with_change_over.iloc[index]).T
    
    ### these are columns specific to order details
    order_columns = [i for i in deckle_order.columns if (i not in layout_columns)
                     & (i not in ['freq', 'layout number'])]
    
    ### for order we grab the last row since this is the real 'completion date'
    order = deckle_order[order_columns].reset_index(drop=True).iloc[-1].dropna()
    
    ### remove widths that are in the deckle opt. but not in the layout
    formula = deckle_layout[layout_columns].reset_index(drop=True).iloc[0].dropna()
    
    ### number of doffs for the given layout/order
    doffs = doffs_in_jumbo
    read_out = ''
    for i in range(formula.shape[0]-1): #for unique prods
        read_out = read_out + ("{}x{} + ".format(formula.index[i], 
                                                formula.iloc[i].astype(int)))
    read_out = read_out + ("{}x{}".format(formula.index[-1], 
                                        formula.iloc[-1].astype(int))) #make last string w/o +
    current = pd.DataFrame([read_out, int(doffs), order]).T
    order = pd.DataFrame(order).T
    order = order.reset_index(drop=True)
    current = pd.DataFrame([read_out, int(doffs)]).T
    current.columns = ['Formula', 'Doffs']
    current = current.join(order)
    
    ### add changeover info
    current_changeover = pd.DataFrame(current.columns)
    current_changeover = current_changeover.set_index(0)
    current_changeover = current_changeover.T
    current_changeover = current_changeover.append({'Order Number': 'Changeover'}, ignore_index=True)
    current_changeover['Completion Date'] = schedule_with_change_over.iloc[index-1]['Completion Date']
    current_combined = current_changeover.append(current, sort=False, ignore_index=True)
    current_combined
#     temp = pd.DataFrame(formula).T
#     temp2 = pd.DataFrame(order).T
#     unformatted_schedule = pd.concat([unformatted_schedule, temp, temp2], sort=False)
#     current.columns = ['Formula', 'Doffs']
    master_schedule = pd.concat([master_schedule, current_combined])
    master_schedule = master_schedule.reset_index(drop=True)

In [18]:
master_schedule.head(50)

,Formula,Doffs,Total LM Order QTY,Width,Scheduled Ship Date,Order Number,Completion Date
0,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 00:50:00.000000
1,170x17 + 208x5,6,2.94118e+06,170,2020-08-05,1,2020-08-12 02:08:27.692308
2,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 02:58:27.692308
3,158x15 + 170x9,6,2.94118e+06,170,2020-08-05,1,2020-08-12 04:16:55.384616
4,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 05:06:55.384616
5,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-05,1,2020-08-12 06:25:23.076924
6,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 06:40:23.076924
7,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-06,2,2020-08-12 07:58:50.769232
8,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 08:13:50.769232
9,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-06,2,2020-08-12 09:32:18.461540
10,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 09:47:18.461540
11,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-06,2,2020-08-12 11:05:46.153848
12,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 11:20:46.153848
13,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-06,2,2020-08-12 12:39:13.846156
14,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 13:29:13.846156
15,154x26,6,3.24675e+06,154,2020-08-07,3,2020-08-12 14:47:41.538464
16,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 15:37:41.538464
17,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-07,4,2020-08-12 16:56:09.230772
18,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 17:11:09.230772
19,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-07,4,2020-08-12 18:29:36.923080
20,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 18:44:36.923080
21,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-07,4,2020-08-12 20:03:04.615388
22,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 20:18:04.615388
23,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-07,4,2020-08-12 21:36:32.307696
24,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 21:51:32.307696
25,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-07,5,2020-08-12 23:10:00.000004
26,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-12 23:25:00.000004
27,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-07,5,2020-08-13 00:43:27.692312
28,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 00:58:27.692312
29,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-07,5,2020-08-13 02:16:55.384620
30,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 02:31:55.384620
31,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-07,5,2020-08-13 03:50:23.076928
32,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 04:40:23.076928
33,218x18,6,2.29358e+06,218,2020-08-07,7,2020-08-13 05:58:50.769236
34,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 06:13:50.769236
35,218x18,6,2.29358e+06,218,2020-08-07,7,2020-08-13 07:32:18.461544
36,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 07:47:18.461544
37,218x18,6,2.29358e+06,218,2020-08-07,8,2020-08-13 09:05:46.153852
38,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 09:55:46.153852
39,154x8 + 158x17,6,3.16456e+06,158,2020-08-13,10,2020-08-13 11:14:13.846160
40,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 12:04:13.846160
41,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-14,11,2020-08-13 13:22:41.538468
42,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 13:37:41.538468
43,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-14,11,2020-08-13 14:56:09.230776
44,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 15:11:09.230776
45,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-14,11,2020-08-13 16:29:36.923084
46,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 16:44:36.923084
47,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-14,11,2020-08-13 18:03:04.615392
48,NaN,NaN,NaN,NaN,NaT,Changeover,2020-08-13 18:53:04.615392
49,208x19,6,2.40385e+06,208,2020-08-14,12,2020-08-13 20:11:32.307700

In [19]:
# master_schedule.to_excel('layouts with completion dates and changeover.xlsx')

In [20]:
# now condense
# do we want to groupby orders, layouts, both?
dff = pd.DataFrame(sorted_schedule_with_order_info.\
                   groupby(['layout number', 'Order Number']).size()).\
                   rename(columns={0: 'Doffs'}).reset_index()

In [21]:
# summary w/o changeover rows

master_schedule = pd.DataFrame()
unformatted_schedule = pd.DataFrame()
for index in dff.index: # pass through layout/order combinations
    order_number = dff.iloc[index]['Order Number']
    
    ### these are columns specific to width layouts
    match = '\d\d\d'
    layout_columns = [i for i in sorted_schedule_with_order_info.columns if re.match(match, i)]
    
    ### match dff grouping with order/layout info in original schedule
    deckle_layout = sorted_schedule_with_order_info.loc\
                    [sorted_schedule_with_order_info['layout number']\
                     == dff.iloc[index]['layout number']]
    
    ### since layout/orders are pareto-ed out in schedule, need to match both
    ### for order completion
    deckle_order =  sorted_schedule_with_order_info.loc\
                    [(sorted_schedule_with_order_info['Order Number']\
                     == dff.iloc[index]['Order Number']) &
                     (sorted_schedule_with_order_info['layout number']\
                     == dff.iloc[index]['layout number'])]
    
    ### these are columns specific to order details
    order_columns = [i for i in deckle_order.columns if (i not in layout_columns)
                     & (i not in ['freq', 'layout number'])]
    
    ### for order we grab the last row since this is the real 'completion date'
    order = deckle_order[order_columns].reset_index(drop=True).iloc[-1].dropna()
    
    ### remove widths that are in the deckle opt. but not in the layout
    formula = deckle_layout[layout_columns].reset_index(drop=True).iloc[0].dropna()
    
    ### number of doffs for the given layout/order
    doffs = dff.iloc[index]['Doffs']
    read_out = ''
    for i in range(formula.shape[0]-1): #for unique prods
        read_out = read_out + ("{}x{} + ".format(formula.index[i], 
                                                formula.iloc[i].astype(int)))
    read_out = read_out + ("{}x{}".format(formula.index[-1], 
                                        formula.iloc[-1].astype(int))) #make last string w/o +
    current = pd.DataFrame([read_out, int(doffs), order]).T
    order = pd.DataFrame(order).T
    order = order.reset_index(drop=True)
    current = pd.DataFrame([read_out, int(doffs)]).T
    current.columns = ['Formula', 'Doffs']
    current = current.join(order)
#     temp = pd.DataFrame(formula).T
#     temp2 = pd.DataFrame(order).T
#     unformatted_schedule = pd.concat([unformatted_schedule, temp, temp2], sort=False)
#     current.columns = ['Formula', 'Doffs']
    master_schedule = pd.concat([master_schedule, current])
    master_schedule = master_schedule.reset_index(drop=True)

In [22]:
master_schedule['Doffs'] = master_schedule['Doffs']*doffs_in_jumbo

In [23]:
# master_schedule.to_excel('layouts with completion dates.xlsx')

In [24]:
master_schedule

,Formula,Doffs,Total LM Order QTY,Width,Scheduled Ship Date,Order Number,Completion Date
0,170x17 + 208x5,6,2.94118e+06,170,2020-08-05,1,2020-08-12 02:08:27.692308
1,158x15 + 170x9,6,2.94118e+06,170,2020-08-05,1,2020-08-12 04:16:55.384616
2,154x2 + 170x7 + 218x2 + 234x9,6,2.94118e+06,170,2020-08-05,1,2020-08-12 06:25:23.076924
3,154x2 + 170x7 + 218x2 + 234x9,24,2.94118e+06,170,2020-08-06,2,2020-08-12 12:39:13.846156
4,154x26,6,3.24675e+06,154,2020-08-07,3,2020-08-12 14:47:41.538464
5,154x2 + 170x7 + 218x2 + 234x9,24,2.94118e+06,170,2020-08-07,4,2020-08-12 21:36:32.307696
6,154x2 + 170x7 + 218x2 + 234x9,24,2.94118e+06,170,2020-08-07,5,2020-08-13 03:50:23.076928
7,218x18,12,2.29358e+06,218,2020-08-07,7,2020-08-13 07:32:18.461544
8,218x18,6,2.29358e+06,218,2020-08-07,8,2020-08-13 09:05:46.153852
9,154x8 + 158x17,6,3.16456e+06,158,2020-08-13,10,2020-08-13 11:14:13.846160
10,154x2 + 170x7 + 218x2 + 234x9,24,2.94118e+06,170,2020-08-14,11,2020-08-13 18:03:04.615392
11,208x19,6,2.40385e+06,208,2020-08-14,12,2020-08-13 20:11:32.307700
12,208x19,12,2.40385e+06,208,2020-08-14,13,2020-08-13 23:18:27.692316
13,170x1 + 218x9 + 234x8,6,2.29358e+06,218,2020-08-14,14,2020-08-14 01:26:55.384624
14,208x14 + 218x5,6,2.29358e+06,218,2020-08-17,18,2020-08-14 03:35:23.076932
15,170x6 + 218x2 + 234x11,42,2.29358e+06,218,2020-08-17,18,2020-08-14 15:04:36.923088
16,154x2 + 170x7 + 218x2 + 234x9,18,2.94118e+06,170,2020-08-19,22,2020-08-14 20:20:00.000012
17,154x2 + 170x7 + 218x2 + 234x9,6,2.29358e+06,218,2020-08-19,23,2020-08-14 21:53:27.692320
18,170x6 + 218x2 + 234x11,42,2.29358e+06,218,2020-08-19,23,2020-08-15 09:22:41.538476
19,170x6 + 218x2 + 234x11,6,2.13675e+06,234,2020-08-24,35,2020-08-15 10:56:09.230784
20,170x6 + 218x2 + 234x11,30,2.94118e+06,170,2020-08-25,37,2020-08-15 18:43:27.692324
21,170x6 + 218x2 + 234x11,24,2.29358e+06,218,2020-08-26,39,2020-08-16 00:57:18.461556
22,154x20,6,3.24675e+06,154,2020-08-27,40,2020-08-16 03:05:46.153864
23,208x19,6,2.40385e+06,208,2020-08-28,45,2020-08-16 05:14:13.846172

In [25]:
df['Date order is complete']

0    2020-08-12 18:22:30.215
1    2020-08-12 22:10:34.426
2    2020-08-13 01:58:38.636
3    2020-08-13 05:46:42.847
4    2020-08-13 09:34:47.057
5    2020-08-13 13:22:51.268
6    2020-08-13 17:10:55.478
7    2020-08-13 20:58:59.689
8    2020-08-14 00:47:03.899
9    2020-08-14 04:35:08.110
10   2020-08-14 08:23:12.320
11   2020-08-14 12:11:16.531
12   2020-08-14 15:59:20.741
13   2020-08-14 19:47:24.952
14   2020-08-14 23:35:29.163
15   2020-08-15 03:23:33.373
16   2020-08-15 07:11:37.584
17   2020-08-15 10:59:41.794
18   2020-08-15 14:47:46.005
19   2020-08-15 18:35:50.215
20   2020-08-15 22:23:54.426
21   2020-08-16 02:11:58.636
22   2020-08-16 06:00:02.847
23   2020-08-16 09:48:07.057
24   2020-08-16 13:36:11.268
25   2020-08-16 17:24:15.478
26   2020-08-16 21:12:19.689
27   2020-08-23 21:12:24.661
28   2020-08-24 01:00:28.871
29   2020-08-24 04:48:33.082
30   2020-08-24 08:36:37.293
31   2020-08-24 12:24:41.503
32   2020-08-24 16:12:45.714
33   2020-08-24 20:00:49.924
34   2020-08-24 23:48:54.135
35   2020-08-25 03:36:58.345
36   2020-08-25 07:25:02.556
37   2020-08-25 11:13:06.766
38   2020-08-25 15:01:10.977
39   2020-08-25 18:49:15.187
40   2020-08-25 22:37:19.398
41   2020-08-26 02:25:23.608
42   2020-08-26 06:13:27.819
43   2020-08-26 10:01:32.029
44   2020-08-26 13:49:36.240
45   2020-08-26 17:37:40.450
46   2020-08-26 21:25:44.661
47   2020-08-27 01:13:48.871
Name: Date order is complete, dtype: datetime64[ns]

In [26]:
def optimize_late_orders(sol, widths, neckin, df, L, set_readable=True):
    """
    Parameters
    ----------
    sol: list
        optimized layouts
    widths: list
        list of product widths
    neckin: list
        list of product neckins
    df: DataFrame
        pandas DataFrame of schedule
    L: int
        put up
    set_readable: Boolean, True False
        if True will make the schedule in Berry format

    """
    extras = pd.DataFrame(np.zeros(len(widths))).T
    master2 = make_layout_registrar(sol, widths, neckin)
    extras.columns = master2.columns[:-1]
    schedule = []
    layout_pattern = 0
    old_width = width = None
    for row1 in df.index:
        current = df.iloc[row1][['Total LM Order QTY', 'Width', 'Scheduled Ship Date']]
        doffs = math.ceil(current['Total LM Order QTY'] / L) # QTY
        width = current['Width']
        if width == old_width:
            layout_pattern -= 1
        master2 = master2.sort_values(width, ascending=False).reset_index(drop=True)
        target_doffs = extras.iloc[0][width]
        print(doffs, width, target_doffs)
        for row in master2.index:
            layout_pattern += 1
            for count in range(master2.iloc[row]['freq'].astype(int)):
                target_doffs += master2.iloc[row][width]
                master2.at[row, 'layout number'] = layout_pattern
                schedule.append(master2.iloc[row])
                master2.at[row, 'freq'] = master2.at[row, 'freq'] - 1

                for master_index in master2.iloc[row].index[:-2]:
                    if (math.isnan(master2.iloc[row][master_index]) == False):
                        extras.iloc[0][master_index] = extras.iloc[0][master_index] + master2.iloc[row][master_index]
                if target_doffs > doffs:
                    break
            else:
                continue
            break
        old_width = width
        extra = target_doffs - doffs
        extras.iloc[0][width] = extra
        clear_output(wait=True)
        print(extras)
        
    
        master_schedule = pd.DataFrame()
        unformatted_schedule = pd.DataFrame()
        sorted_schedule = pd.DataFrame(schedule)
        dff = pd.DataFrame(sorted_schedule.groupby('layout number').size()).rename(columns={0: 'Doffs'}).reset_index()
        for layout_number in dff['layout number']:
            deckle = sorted_schedule.loc[sorted_schedule['layout number'] == layout_number]
            formula = deckle.reset_index(drop=True).iloc[0].dropna()
            freq = dff.loc[dff['layout number'] == layout_number]['Doffs'].values[0]
            read_out = ''
            for i in range(formula.shape[0]-3): #for unique prods
                read_out = read_out + ("{}x{} + ".format(formula.index[i], formula.iloc[i].astype(int)))

            read_out = read_out + ("{}x{}".format(formula.index[-3], formula.iloc[-3].astype(int))) #make last string w/o +
            current = pd.DataFrame([read_out, int(freq)]).T
            temp = pd.DataFrame(formula).T
            temp = temp[temp.columns[:-1]]
            unformatted_schedule = pd.concat([unformatted_schedule, temp], sort=False)
            current.columns = ['Formula', 'Doffs']
            master_schedule = pd.concat([master_schedule, current])
        master_schedule = master_schedule.reset_index(drop=True)
    if set_readable == False:
        master_schedule = unformatted_schedule
        
    return master_schedule

In [27]:
master_schedule.to_excel('temp.xlsx', index=False)