**jumbo rolls are folded in**

**changeover between jumbos are folded in**

**Minimize knife changes folded in**

need to ..

* show when an order in the future has been fullfilled.

* look forward in schedule to optimize new/better layouts

* make layout table editable

* speed test algorithm

* LM get rid of decimals

check work orders to full jumbo

other 

* student help

For next time: the time (knife changes) scheduler isn't working for Quality/SM/cycle 1. May be due to order being shorter - there being some mismatch between jumbos and actual LM quatnityt. find_optimum is finding the right number of jumbos, display_layout is creating the correct layout.

# Simple Genetic Algorithm to Optimize Deckle Loss

In [81]:
import sys
sys.path.append("../")

In [82]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import math
from random import shuffle, choice
import copy
from utils import *
from genetic import *
from IPython.display import clear_output
import time
import datetime
import re

In [83]:
df = pd.read_excel('../data/200721_ New Way SCH W3-W6 W14 07.20.20.xlsx',
                   sheet_name='Schedule')

# the input schedule appears as a data table on the dashboard
# this is used to select what to deckle
df_input_schedule = pd.read_excel('../data/200721_ New Way SCH W3-W6 W14 07.20.20.xlsx',
                   sheet_name='Schedule')
df_input_schedule.insert(1, 'Technology', df_input_schedule['Description'].apply(lambda x: parse_description(x, 'tech')))
df_input_schedule.insert(2, 'Color', df_input_schedule['Description'].apply(lambda x: x.split(';')[1] if type(x) == str else None))
df_input_schedule.insert(3, 'Width', df_input_schedule['Description'].apply(lambda x: parse_description(x, 'width')))
df_input_schedule = df_input_schedule[[col for col in df_input_schedule.columns if 'Unnamed' not in str(col)]]
df_input_schedule['Total LM Order QTY'] = df_input_schedule['Total LM Order QTY'].round(1)

In [84]:
temp = df_input_schedule[['Customer Name', 'Technology', 'Color', 'Width', 'CYCLE / BUCKET',
                          'Description', 'Total LM Order QTY',
                          'Scheduled Ship Date', 'Date order is complete']]
temp.loc[:,'Scheduled Ship Date'] = pd.to_datetime(temp['Scheduled Ship Date'], errors='coerce')
temp.loc[:,"Scheduled Ship Date"] = temp["Scheduled Ship Date"].dt.strftime("%Y-%m-%d")

temp.loc[:,"Date order is complete"] = temp["Date order is complete"].dt.round('T')

/home/wab665/anaconda3/envs/py37/lib/python3.8/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [85]:
temp.head()

,Customer Name,Technology,Color,Width,CYCLE / BUCKET,Description,Total LM Order QTY,Scheduled Ship Date,Date order is complete
0,P & G,SAM,WHITE,208,CYCLE 1,SAM0130UN0208;WHITE;300,369822.5,2020-07-21,2020-07-20 13:05:00
1,P & G,SAM,WHITE,170,CYCLE 1,SAM0130UN0170;WHITE;300,2262443.4,2020-07-21,2020-07-20 16:01:00
2,P & G,SAM,WHITE,234,CYCLE 1,SAM0130UN0234;WHITE;300,2005259.7,2020-07-22,2020-07-20 19:35:00
3,P & G,SAM,WHITE,234,CYCLE 1,SAM0130UN0234;WHITE;300,2136752.1,2020-07-22,2020-07-20 23:23:00
4,P & G,SAM,WHITE,234,CYCLE 1,SAM0130UN0234;WHITE;300,2136752.1,2020-07-22,2020-07-21 03:11:00

In [86]:
# temp = temp[temp['Scheduled Ship Date'].apply(lambda x: type(x) == int)]                          
temp_json = temp.to_json()

In [87]:
temp2 = pd.read_json(temp_json, 
                     convert_dates=['Scheduled Ship Date', 'Date order is complete'])

## to_datetime and to_json use default units ms and ns, respectively
temp2['Scheduled Ship Date'] = pd.to_datetime(temp2['Scheduled Ship Date'], 
                                              errors='coerce', unit='ms')

In [88]:
temp2["Scheduled Ship Date"] = temp2["Scheduled Ship Date"].dt.strftime("%Y-%m-%d")

In [89]:
for i, x in enumerate(temp2['Scheduled Ship Date']):
    if type(x) == pd._libs.tslibs.timestamps.Timestamp:
        temp2.loc[i, 'Scheduled Ship Date'] = datetime.datetime.strftime(x, '%Y-%m-%d')

In [90]:
temp2

,Customer Name,Technology,Color,Width,CYCLE / BUCKET,Description,Total LM Order QTY,Scheduled Ship Date,Date order is complete
0,P & G,SAM,WHITE,208.0,CYCLE 1,SAM0130UN0208;WHITE;300,369822.5,2020-07-21,2020-07-20 13:05:00
1,P & G,SAM,WHITE,170.0,CYCLE 1,SAM0130UN0170;WHITE;300,2262443.4,2020-07-21,2020-07-20 16:01:00
2,P & G,SAM,WHITE,234.0,CYCLE 1,SAM0130UN0234;WHITE;300,2005259.7,2020-07-22,2020-07-20 19:35:00
3,P & G,SAM,WHITE,234.0,CYCLE 1,SAM0130UN0234;WHITE;300,2136752.1,2020-07-22,2020-07-20 23:23:00
4,P & G,SAM,WHITE,234.0,CYCLE 1,SAM0130UN0234;WHITE;300,2136752.1,2020-07-22,2020-07-21 03:11:00
...,...,...,...,...,...,...,...,...,...
355,CARDINAL HEALTH,SM,WHITE,575.0,CYCLE 6,SM10120UN0575;WHITE;300,18985507.2,NaT,2020-12-25 14:58:00
356,None,None,None,NaN,CYCLE 6,None,NaN,NaT,2020-12-25 15:28:00
357,P & G,SM,WHITE,80.0,CYCLE 6,SM30330UN0080;WHITE;600,28030303.0,NaT,2020-12-27 20:40:00
358,IRVING CONSUMER PRODUCTS,SM,WHITE,80.0,CYCLE 6,SM30330UN0080;WHITE;600,7575757.6,NaT,2020-12-28 11:03:00
359,Allotted trial time,None,None,NaN,CYCLE 6,None,NaN,NaT,2020-12-28 23:03:00

In [91]:
### not currently used, grabs indicated information
customer_names = [i for i in df['Customer Name'].unique() if type(i) == str]
technologies = list(set([parse_description(i, 'tech') for i in df['Description'] 
                         if (type(i) == str)]))
technologies = [i for i in technologies if i]
colors = list(set([i[1] for i in list(df['Description']
                .str.split(';')) if type(i) == list]))
cycles = list(df['CYCLE / BUCKET'].unique())

In [94]:
customer = 'FIRST QUALITY PRODUCTS'
technology = 'SM' # Technology -> 
color = 'DENBLUE'
cycle = 'CYCLE 1'

# customer = 'P & G'
# technology = 'SAM'
# color = 'WHITE'
# cycle = 'CYCLE 1'

df_filtered = df.loc[df['Customer Name'] == customer]
df_filtered = df_filtered.loc[df_filtered['Description'].str.contains(technology)]
df_filtered = df_filtered.loc[df_filtered['Description'].str.contains(color)] #CYAN, TEAL
df_filtered = df_filtered.loc[df_filtered['CYCLE / BUCKET'] == cycle]
df_filtered = df_filtered.loc[df_filtered['Total LM Order QTY'] > 0]
df_filtered.insert(0, 'Block', 1)
df_filtered = df_filtered.reset_index(drop=True)
df_filtered['Order Number'] = df_filtered.index + 1

df_filtered['Width'] = pd.DataFrame(list(pd.DataFrame(list(df_filtered['Description']
                                                  .str.split(';')))[0].str.split('UN0')))[1]
df_filtered.head(10)

,Block,SPM375014 PROD. DATE,CYCLE / BUCKET,Customer Name,Item No,WO#,Description,Treatment,KG,Hours To Produce,...,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,% reclaim,Amount Repro needed,Type of Repro,Order Number,Width
0,1,2020-07-25 15:55:11.795,CYCLE 1,FIRST QUALITY PRODUCTS,1790263,82349245,SM30110UN0670;DENBLUE;600,UNTREATED,5500.0,3.806228,...,NaN,NaN,NaN,NaN,NaN,0.15,1981.588235,SMS,1,670
1,1,2020-07-25 19:43:34.217,CYCLE 1,FIRST QUALITY PRODUCTS,1790262,82349246,SM30110UN0510;DENBLUE;600,UNTREATED,5500.0,3.806228,...,NaN,NaN,NaN,NaN,NaN,0.15,1981.588235,SMS,2,510
2,1,2020-07-25 23:31:56.639,CYCLE 1,FIRST QUALITY PRODUCTS,1790261,82349250,SM30110UN0245;DENBLUE;600,UNTREATED,2200.0,1.522491,...,NaN,NaN,NaN,NaN,NaN,0.15,1981.588235,SMS,3,245
3,1,2020-07-26 01:03:17.608,CYCLE 1,FIRST QUALITY PRODUCTS,1789190,82327051,SM30110UN0440;DENBLUE;600,UNTREATED,6600.0,4.567474,...,NaN,NaN,NaN,NaN,NaN,0.15,1981.588235,SMS,4,440
4,1,2020-07-26 05:37:20.515,CYCLE 1,FIRST QUALITY PRODUCTS,1789191,82327039,SM30110UN0600;DENBLUE;600,UNTREATED,8800.0,6.089965,...,NaN,NaN,NaN,NaN,NaN,0.15,1981.588235,SMS,5,600
5,1,2020-07-26 11:42:44.390,CYCLE 1,FIRST QUALITY PRODUCTS,1755582,82321375,SM30110UN0454;DENBLUE;600,UNTREATED,6600.0,4.567474,...,NaN,NaN,NaN,NaN,NaN,0.15,1981.588235,SMS,6,454

In [139]:
[math.ceil(x/L) for x in lm] # jumbos needed per width, rounded up

[9, 14, 13, 10, 14, 8]

In [134]:
lm

[816326.530612245,
 1363636.3636363635,
 1321585.9030837005,
 980392.1568627451,
 1333333.3333333335,
 746268.6567164179]

In [136]:
widths

[245, 440, 454, 510, 600, 670]

In [135]:
df_filtered['Total LM Order QTY']

0    7.462687e+05
1    9.803922e+05
2    8.163265e+05
3    1.363636e+06
4    1.333333e+06
5    1.321586e+06
Name: Total LM Order QTY, dtype: float64

In [95]:
### Detects if there is a break in the rolls coming of the
### line

prev_index = df_filtered.index[0] - 1
block = 1
for index in df_filtered.index:
    if index != prev_index + 1:
        block += 1
    df_filtered.loc[index, 'Block'] = block
    prev_index = index

In [96]:
list(df_filtered.groupby('Width')['Total LM Order QTY'].sum().index.values.astype(int))

[245, 440, 454, 510, 600, 670]

In [97]:
lm = list(df_filtered.groupby('Description')['Total LM Order QTY'].sum().values)
widths = list(df_filtered.groupby('Width')['Total LM Order QTY'].sum().index.values.astype(int))
doffs_in_jumbo = 6
B = 4160
L = doff_length = 17000 * doffs_in_jumbo # df['LM putup']

# neckin = [4, 4, 5, 7, 7, 7] # 158 missing in cycle 1, 4 mm knife in
neckins = []
for width in widths:
    if width < 170:
        neckin = 4
    elif width < 208:
        neckin = 5
    else:
        neckin = 7
    neckins.append(neckin)
w = list(np.array(widths) + np.array(neckin)) # the values used in the actual computation
q = [math.ceil(x/L) for x in lm] # jumbos needed per width, rounded up
s = BinPackingExample(w, q) # material orders (list of widths, 1 width = 1 jumbo)

print('The important variables', end='\n\n')
print('widths: {} (mm)'.format(widths))
print('neck in: {} (mm)'.format(neckins))
print('L (m): {}'.format(L))
print('undeckled jumbos needed: {}'.format(q))

The important variables

widths: [245, 440, 454, 510, 600, 670] (mm)
neck in: [7, 7, 7, 7, 7, 7] (mm)
L (m): 102000
undeckled jumbos needed: [9, 14, 13, 10, 14, 8]

In [156]:
# check that s has proper amount of jumbos
from collections import Counter
Counter(s)

Counter({252: 9, 461: 13, 517: 10, 447: 14, 677: 8, 607: 14})

In [98]:
# customer = 'P & G'
# product = 'SAM' # Technology -> 
# color = 'WHITE'
# cycle = 'CYCLE 2'

# df = pd.read_excel('../data/berry/200721_ New Way SCH W3-W6 W14 07.20.20.xlsx',
#                    sheet_name='Schedule')
# df = df.loc[df['Customer Name'] == customer]
# df = df.loc[df['Description'].str.contains(product)]
# df = df.loc[df['Description'].str.contains(color)] #CYAN, TEAL
# df = df.loc[df['CYCLE / BUCKET'] == cycle]
# df = df.reset_index(drop=True)
# df['Width'] = pd.DataFrame(list(pd.DataFrame(list(df['Description']
#                                                   .str.split(';')))[0].str.split('UN0')))[1]
# lm = list(df.groupby('Description')['Total LM Order QTY'].sum().values)
# widths = list(df.groupby('Width')['Total LM Order QTY'].sum().index.values.astype(int))
# doffs_in_jumbo = 6
# B = 4160
# L = doff_length = 17000 * doffs_in_jumbo # df['LM putup']

# neckin = [4, 4, 5, 7, 7, 7] # 158 missing in cycle 1, 4 mm knife in
# w = list(np.array(widths) + np.array(neckin))
# q = [math.ceil(x/L) for x in lm]
# print("max doffs needed without stock cutting: {}".format(q))
# s = BinPackingExample(w, q)
# df_json = df.to_json()

if we gave each order its own entire row we would produce a lot of wasted material

# Run Deckle Optimizer

In [142]:
widths

[245, 440, 454, 510, 600, 670]

In [174]:
sol, loss = find_optimum(s, B, widths, neckins, max_unique_products=4, 
                         loss_target=12, max_doff_layouts=10)

10.248397435897436

In [149]:
# def find_optimum(s,
#              B,
#              widths,
#              neckin,
             
loss_target = 12
max_doff_layouts = 20
max_unique_products = 6
gene_count = 5
doff_min = 1


losses = []
solutions = []
best_loss = 100
step = 0
start_time = time.time()

while True:
    step += 1
    shuffle(s)
    remain = [B] #initialize list of remaining bin spaces
    sol = [[]]
    binlim = np.inf

    for item in s:#sorted(s, reverse=True): # iter through products
        for j,free in enumerate(remain): #
            if (free >= item) and (len(sol[j]) < binlim): # if theres room
                remain[j] -= item
                sol[j].append(item)
                break
        else: # at this step we need to double the previous (or mult. by min. doff count)
            sol.append([item]) #starts new list in sol list
            remain.append(B-item) #append a new bin and subtract the width of the new item

    genes = []

    df = pd.DataFrame(sol)
    df = df.fillna(0)
    dff = pd.DataFrame(df.groupby(list(df.columns)).size()).\
        rename(columns={0: 'freq'}).reset_index()
    dff = dff[dff.columns[:-1]]
    dff["Loss"] = B - dff.sum(axis=1)
    dff = dff.loc[dff.replace(0, np.nan, inplace=False).nunique(axis=1) <= max_unique_products]
    dff = dff.loc[dff['Loss'] < 100]
    dff = dff.sort_values('Loss').head(gene_count).reset_index(drop=True)

    dff = dff[dff.columns[:-1]]
    dff = dff.fillna(0)

    for row in dff.index:
        gene = list(dff.iloc[row].values)
        gene = [i for i in gene if i != 0]
        genes.append(gene)

    order_remaining = copy.copy(s)
    sol2 = []
    gene_time = time.time() - start_time

    while True:
        backup_order_remaining = copy.copy(order_remaining)
        try:
            new_gene = list(choice(genes))
        except:
            break
        if new_gene in sol2:
            sol2.append(new_gene)
            for item in new_gene:
                if item in order_remaining:
                    order_remaining.remove(item)
                elif item == 0:
                    pass
                else: # new gene over produces item
                    order_remaining = backup_order_remaining
                    sol2.remove(new_gene)
                    genes.remove(new_gene)
                    break
        else:
            check_pass = True
            for mult in range(doff_min):

                for item in new_gene:
                    if item in order_remaining:
                        order_remaining.remove(item)
                    elif item == 0:
                        pass
                    else: # new gene over produces item

                        check_pass = False
                        break
                else:

                    continue  # only executed if the inner loop did NOT break
                if check_pass == False:  # only executed if the inner loop DID break
                    order_remaining = backup_order_remaining
                    genes.remove(new_gene)

                    break
            if check_pass == True:
                for mult in range(doff_min):
                    sol2.append(new_gene)

    chrome_time = time.time() - gene_time
    #     if step > iterations:
    #         break
    remain2 = [B] #initialize list of remaining bin spaces
#         print(remain2)
    sol3 = [[]]
    binlim = np.inf
    doff_min = 2
    for item in sorted(order_remaining, reverse=True): # iter through products
        for j,free in enumerate(remain2): #
            if (free >= item) and (len(sol3[j]) < binlim): # if theres room,
                remain2[j] -= item # and we haven't reach bimlim
                sol3[j].append(item)
                break
        else: # at this step we need to double the previous (or mult. by min. doff count)
            sol3.append([item]) #starts new list in sol list
            remain2.append(B-item) #append a new bin and subtract the width of the new item
            # subtract
    # loss = sum(remain2) / np.sum(np.sum(sol3)) * 100
    ffd_time = time.time() - chrome_time
    sol_tot = sol2 + sol3
    space_avail = len(sol_tot) * B
    loss = (space_avail - np.sum(np.sum(sol_tot))) / space_avail * 100
    losses.append(loss)
    solutions.append(sol_tot)
    if loss < best_loss:
        best_solution = sol_tot
        best_loss = loss
        print(best_loss)

    if (loss < loss_target) and \
        (summarize_results(sol_tot, widths, neckin, B).shape[0] <
        (max_doff_layouts+1)) and \
        (all(pd.DataFrame(sol_tot).replace(0, np.nan, inplace=False)\
        .nunique(axis=1) <= max_unique_products)):
        break
# return sol_tot, loss

10.248397435897436

In [161]:
Counter(order_remaining)

Counter({461: 6, 252: 5, 607: 4, 517: 4, 447: 1})

In [160]:
def flatten(seq, container=None):
    if container is None:
        container = []

    for s in seq:
        try:
            iter(s)  # check if it's iterable
        except TypeError:
            container.append(s)
        else:
            flatten(s, container)

    return container

Counter({517.0: 10, 677.0: 8, 607.0: 14, 447.0: 14, 461.0: 13, 252.0: 9})

In [170]:
# check if find_optimum() creates the right number of jumbos

print(Counter(flatten(sol_tot))-Counter(s))
print((Counter(s)))
print(Counter(flatten(sol_tot)))

Counter()
Counter({447: 14, 607: 14, 461: 13, 517: 10, 252: 9, 677: 8})
Counter({607.0: 14, 447.0: 14, 461.0: 13, 517.0: 10, 252.0: 9, 677.0: 8})

# Build Layout for Dashboard View

In [176]:
sol

[[677, 677, 677, 677, 677, 677],
 [677, 677, 607, 607, 607, 607, 252],
 [607, 607, 607, 607, 607, 607, 517],
 [607, 607, 607, 607, 517, 517, 517],
 [517, 517, 517, 517, 517, 517, 461, 461],
 [461, 461, 461, 461, 461, 461, 461, 461, 461],
 [461, 461, 447, 447, 447, 447, 447, 447, 447],
 [447, 447, 447, 447, 447, 447, 447, 252, 252, 252, 252],
 [252, 252, 252, 252]]

In [175]:
layout_summary(sol, widths, neckins, B)

,0,1,2,3,4,5,6,7,8,9,10,Doffs,Loss
Doffs,,,,,,,,,,,,,
1,245,245,245,245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3152.0
1,440,440,440,440,440.0,440.0,440.0,245.0,245.0,245.0,245.0,1,23.0
1,454,454,440,440,440.0,440.0,440.0,440.0,440.0,NaN,NaN,1,109.0
1,454,454,454,454,454.0,454.0,454.0,454.0,454.0,NaN,NaN,1,11.0
1,510,510,510,510,510.0,510.0,454.0,454.0,NaN,NaN,NaN,1,136.0
1,600,600,600,600,510.0,510.0,510.0,NaN,NaN,NaN,NaN,1,181.0
1,600,600,600,600,600.0,600.0,510.0,NaN,NaN,NaN,NaN,1,1.0
1,670,670,600,600,600.0,600.0,245.0,NaN,NaN,NaN,NaN,1,126.0
1,670,670,670,670,670.0,670.0,NaN,NaN,NaN,NaN,NaN,1,98.0

# Run Master Schedule, Optimizing Either for On-Time Orders or Fastest Schedule

In [102]:
setup_df = pd.read_excel('../data/200725_WAVA Deckle Optimization Parameters Rev1.xlsx',
                         sheet_name='Deckle Parameters')
speed_df = pd.read_excel('../data/200725_WAVA Deckle Optimization Parameters Rev1.xlsx',
                         sheet_name='Product Parameters')

In [115]:
start_date_time = datetime.datetime(2020,8,1)
start_date_time

datetime.datetime(2020, 8, 1, 0, 0)

In [104]:
extras = pd.DataFrame(np.zeros(len(widths))).T
extras

     0    1    2    3    4    5
0  0.0  0.0  0.0  0.0  0.0  0.0

In [105]:
master2 = make_layout_registrar(sol, widths, neckins)
master2

../utils.py:490: FutureWarning:

Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

   245  440  454  510  600  670  freq
0  4.0  NaN  NaN  NaN  NaN  NaN     1
0  4.0  7.0  NaN  NaN  NaN  NaN     1
0  NaN  7.0  2.0  NaN  NaN  NaN     1
0  NaN  NaN  9.0  NaN  NaN  NaN     1
0  NaN  NaN  2.0  6.0  NaN  NaN     1
0  NaN  NaN  NaN  3.0  4.0  NaN     1
0  NaN  NaN  NaN  1.0  6.0  NaN     1
0  1.0  NaN  NaN  NaN  4.0  2.0     1
0  NaN  NaN  NaN  NaN  NaN  6.0     1

In [106]:
widths

[245, 440, 454, 510, 600, 670]

In [107]:
master2

   245  440  454  510  600  670  freq
0  4.0  NaN  NaN  NaN  NaN  NaN     1
0  4.0  7.0  NaN  NaN  NaN  NaN     1
0  NaN  7.0  2.0  NaN  NaN  NaN     1
0  NaN  NaN  9.0  NaN  NaN  NaN     1
0  NaN  NaN  2.0  6.0  NaN  NaN     1
0  NaN  NaN  NaN  3.0  4.0  NaN     1
0  NaN  NaN  NaN  1.0  6.0  NaN     1
0  1.0  NaN  NaN  NaN  4.0  2.0     1
0  NaN  NaN  NaN  NaN  NaN  6.0     1

In [108]:
make_layout_registrar(sol, widths, neckins)

   245  440  454  510  600  670  freq
0  4.0  NaN  NaN  NaN  NaN  NaN     1
0  4.0  7.0  NaN  NaN  NaN  NaN     1
0  NaN  7.0  2.0  NaN  NaN  NaN     1
0  NaN  NaN  9.0  NaN  NaN  NaN     1
0  NaN  NaN  2.0  6.0  NaN  NaN     1
0  NaN  NaN  NaN  3.0  4.0  NaN     1
0  NaN  NaN  NaN  1.0  6.0  NaN     1
0  1.0  NaN  NaN  NaN  4.0  2.0     1
0  NaN  NaN  NaN  NaN  NaN  6.0     1

In [109]:
neckin=neckins
extras = pd.DataFrame(np.zeros(len(widths))).T
master2 = make_layout_registrar(sol, widths, neckin)
master2.columns = master2.columns.str.strip()
if DEBUG:
    print(master2.head())
extras.columns = master2.columns[:-1]
schedule = []
schedule_with_order_info = []
layout_pattern = 0
old_width = width = None
completed_orders = []
df_filtered['Order Number'] = df_filtered.index + 1

   245  440  454  510  600  670  freq
0  4.0  NaN  NaN  NaN  NaN  NaN     1
0  4.0  7.0  NaN  NaN  NaN  NaN     1
0  NaN  7.0  2.0  NaN  NaN  NaN     1
0  NaN  NaN  9.0  NaN  NaN  NaN     1
0  NaN  NaN  2.0  6.0  NaN  NaN     1

In [110]:
sol

[[677, 677, 677, 677, 677, 677],
 [677, 677, 607, 607, 607, 607, 252],
 [607, 607, 607, 607, 607, 607, 517],
 [607, 607, 607, 607, 517, 517, 517],
 [517, 517, 517, 517, 517, 517, 461, 461],
 [461, 461, 461, 461, 461, 461, 461, 461, 461],
 [461, 461, 447, 447, 447, 447, 447, 447, 447],
 [447, 447, 447, 447, 447, 447, 447, 252, 252, 252, 252],
 [252, 252, 252, 252]]

In [123]:

# def optimize_schedule(sol, widths, neckin, df_filtered, L, setup_df, speed_df,
#                   doffs_in_jumbo, start_date_time, 
neckin=neckins
objective='Time (Knife Changes)'
# objective='Late Orders'
DEBUG=True

#####################################################
# Step 1: Create Schedule According to Order Sequence
#####################################################
extras = pd.DataFrame(np.zeros(len(widths))).T
master2 = make_layout_registrar(sol, widths, neckin)
master2.columns = master2.columns.str.strip()
if DEBUG:
    print(master2.head())
extras.columns = master2.columns[:-1]
schedule = []
schedule_with_order_info = []
layout_pattern = 0
old_width = width = None
completed_orders = []
df_filtered['Order Number'] = df_filtered.index + 1

if objective == 'Late Orders':
    #### logic for jumbo rolls should go in first loop
    for row1 in df_filtered.index:
        clear_output(wait=True)
        ### select schedule data
        current_scheduled = df_filtered.iloc[row1][['Total LM Order QTY', 'Width', 'Scheduled Ship Date']]
        current_scheduled['Order Number'] = row1+1
        ship_date = current_scheduled['Scheduled Ship Date']
        doffs = math.ceil(current_scheduled['Total LM Order QTY'] / L) # QTY
        width = str(current_scheduled['Width'])
        if DEBUG:
            print(width)

        ### check if we've entered a new product
        ### no setup changes here, we need to see if the layout has changed
        if width == old_width:
            layout_pattern -= 1

        ### sort by the current scheduled width in master 2
        master2 = master2.sort_values(str(width), ascending=False)
        master2 = master2.reset_index(drop=True)
        if DEBUG:
            print(master2.head())

        ### calc how many new doffs need to be made from inventory
        target_doffs = extras.iloc[0][width]
        if DEBUG:
            print(pd.DataFrame(data=[[doffs, width, target_doffs]],
                               columns=['required doffs', 'width', 'doffs made']))
            print(doffs, width, target_doffs)

        ### only proceed if doffs are available in layout registrar
        ### and not in inventory
        if ((any(master2.loc[master2[width] > 0]['freq'] > 0))
            and (target_doffs <= doffs)):

        ### go through the rows in the master2 registrar and check for
        ### layout patterns that contain our current width

        ### Every row is a new layout unless the outer
        ### loop has incremented, then only maybe is it
        ### a new layout
            for row in master2.index:

                # if none of the width are in the layout then break out
                if np.isnan(master2.iloc[row][width]):
                    break
                layout_pattern += 1

                # looping through available doffs in the layout
                for count in range(master2.iloc[row]['freq'].astype(int)):

                    # add to target doffs
                    target_doffs += master2.iloc[row][width]

                    # add to number of times we've made this layout
                    master2.at[row, 'layout number'] = layout_pattern


                    new_layout_and_scheduled_product = pd.concat([master2.iloc[row],
                                                                  current_scheduled])
                    schedule_with_order_info.append(new_layout_and_scheduled_product)
                    schedule.append(master2.iloc[row])
                    master2.at[row, 'freq'] = master2.at[row, 'freq'] - 1

                    ### Tabluate the other widths that were made on the layout
                    for master_index in master2.iloc[row].index[:-2]:
                        if (math.isnan(master2.iloc[row][master_index]) == False):
                            ### tabulate extras for other widths in the layout
                            extras.iloc[0][master_index] = extras.iloc[0][master_index] +\
                                master2.iloc[row][master_index]
                            completed_orders.append
                    if target_doffs >= doffs:

                        ### add to registrar of completed orders.
                        completed_orders.append(current_scheduled['Order Number'])

                        ### now that we've finished this order, we want to see if we've completed any other orders as well


                        break
                ### for exiting nested for loop
                else:
                    continue
                break
        old_width = width
        extra = target_doffs - doffs
        extras.iloc[0][width] = extra
        if DEBUG:
            print(extras)

    sorted_schedule_with_order_info = pd.DataFrame(schedule_with_order_info)
    sorted_schedule_with_order_info = sorted_schedule_with_order_info.reset_index(drop=True)
    sorted_schedule = pd.DataFrame(schedule)
    sorted_schedule = sorted_schedule.reset_index(drop=True)
elif objective == "Time (Knife Changes)":
    # when we sort master, this will be similar to how we sort
    # according to the desirable width in the optimize for late
    # order algorithm. We will however do this for every width

    for width in widths:
        master2 = master2.sort_values(str(width), ascending=False)
        master2 = master2.reset_index(drop=True)

    # now we need to go through the schedule and match layouts
    # with orders

    # go through the layouts
    for row in master2.index:

        # go through doffs in the layout
        for count in range(master2.iloc[row]['freq'].astype(int)):

            # here we will grow our extras dataframe. We will use this
            # to check against orders that are fullfilled.

            ### Tabluate the other widths that were made on the layout
            for master_index in master2.iloc[row].index[:-1]: # no layout number col, -2 in other algorithm

                if (math.isnan(master2.iloc[row][master_index]) == False):

                    ### tabulate extras for other widths in the layout
                    extras.iloc[0][master_index] = extras.iloc[0][master_index] +\
                        master2.iloc[row][master_index]

            # go through the orders
            added_this_roll = []
            if df_filtered.shape[0] > 0:
                for row1 in df_filtered.index:
                    current_scheduled = df_filtered.iloc[row1][['Total LM Order QTY', 'Width',
                                                                     'Scheduled Ship Date',
                                                                     'Order Number']]
                    
                    order_number = current_scheduled['Order Number']
                    ship_date = current_scheduled['Scheduled Ship Date']
                    doffs = math.ceil(current_scheduled['Total LM Order QTY'] / L) # QTY
                    width = str(current_scheduled['Width'])
                    if extras[width][0] > doffs:
                        

                        completed_orders.append(order_number)
                        extra = extras[width][0] - doffs
                        extras.iloc[0][width] = extra
                        new_layout_and_scheduled_product = pd.concat([master2.iloc[row],
                                                                      current_scheduled])
                        schedule_with_order_info.append(new_layout_and_scheduled_product)
                        added_this_roll.append(order_number)
            # if no order completed just append the layout
            if len(added_this_roll) == 0:
                schedule_with_order_info.append(master2.iloc[row])
            # if two orders completed append both
            elif len(added_this_roll) == 2:
                schedule_with_order_info[-1][-1] =  "{} and {}".format(added_this_roll[0], added_this_roll[1])
                schedule_with_order_info.pop(-2)
            elif len(added_this_roll) > 2:
                print('this is not tested')
                schedule_with_order_info[-1][-1] = str(added_this_roll).split('[')[-1].split(']')[0]
                # schedule_with_order_info.pop(-len(added_this_roll))
            df_filtered = df_filtered[~df_filtered['Order Number'].isin(completed_orders)]
            df_filtered = df_filtered.reset_index(drop=True)
            master2.loc[0, 'freq'] -= 1


    sorted_schedule_with_order_info = pd.DataFrame(schedule_with_order_info)
    sorted_schedule_with_order_info = sorted_schedule_with_order_info.reset_index(drop=True)
    sorted_schedule_with_order_info[['Total LM Order QTY',
   'Width', 'Scheduled Ship Date', 'Order Number']] = \
    sorted_schedule_with_order_info[['Total LM Order QTY',
   'Width', 'Scheduled Ship Date', 'Order Number']].fillna(method='bfill')

   245  440  454  510  600  670  freq
0  4.0  NaN  NaN  NaN  NaN  NaN     1
0  4.0  7.0  NaN  NaN  NaN  NaN     1
0  NaN  7.0  2.0  NaN  NaN  NaN     1
0  NaN  NaN  9.0  NaN  NaN  NaN     1
0  NaN  NaN  2.0  6.0  NaN  NaN     1
Total LM Order QTY                  746269
Width                                  670
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             1
Name: 0, dtype: object
Total LM Order QTY                  980392
Width                                  510
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             2
Name: 1, dtype: object
Total LM Order QTY                  816327
Width                                  245
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             3
Name: 2, dtype: object
Total LM Order QTY             1.36364e+06
Width                                  440
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             4
Name: 3, dtype: object
Total LM Order QTY             1.33333e+06
Width                                  600
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             5
Name: 4, dtype: object
Total LM Order QTY             1.32159e+06
Width                                  454
Scheduled Ship Date    2020-08-26 00:00:00
Order Number                             6
Name: 5, dtype: object
Total LM Order QTY                  746269
Width                                  670
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             1
Name: 0, dtype: object
Total LM Order QTY                  980392
Width                                  510
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             2
Name: 1, dtype: object
Total LM Order QTY                  816327
Width                                  245
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             3
Name: 2, dtype: object
Total LM Order QTY             1.36364e+06
Width                                  440
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             4
Name: 3, dtype: object
Total LM Order QTY             1.33333e+06
Width                                  600
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             5
Name: 4, dtype: object
Total LM Order QTY             1.32159e+06
Width                                  454
Scheduled Ship Date    2020-08-26 00:00:00
Order Number                             6
Name: 5, dtype: object
Total LM Order QTY                  746269
Width                                  670
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             1
Name: 0, dtype: object
Total LM Order QTY                  980392
Width                                  510
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             2
Name: 1, dtype: object
Total LM Order QTY                  816327
Width                                  245
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             3
Name: 2, dtype: object
Total LM Order QTY             1.36364e+06
Width                                  440
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             4
Name: 3, dtype: object
Total LM Order QTY             1.33333e+06
Width                                  600
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             5
Name: 4, dtype: object
Total LM Order QTY             1.32159e+06
Width                                  454
Scheduled Ship Date    2020-08-26 00:00:00
Order Number                             6
Name: 5, dtype: object
Total LM Order QTY                  746269
Width                                  670
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             1
Name: 0, dtype: object
Total LM Order QTY                  980392
Width                                  510
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             2
Name: 1, dtype: object
Total LM Order QTY                  816327
Width                                  245
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             3
Name: 2, dtype: object
Total LM Order QTY             1.36364e+06
Width                                  440
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             4
Name: 3, dtype: object
Total LM Order QTY             1.33333e+06
Width                                  600
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             5
Name: 4, dtype: object
Total LM Order QTY             1.32159e+06
Width                                  454
Scheduled Ship Date    2020-08-26 00:00:00
Order Number                             6
Name: 5, dtype: object
Total LM Order QTY                  746269
Width                                  670
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             1
Name: 0, dtype: object
Total LM Order QTY                  980392
Width                                  510
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             2
Name: 1, dtype: object
Total LM Order QTY                  816327
Width                                  245
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             3
Name: 2, dtype: object
Total LM Order QTY             1.36364e+06
Width                                  440
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             4
Name: 3, dtype: object
Total LM Order QTY             1.33333e+06
Width                                  600
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             5
Name: 4, dtype: object
Total LM Order QTY             1.32159e+06
Width                                  454
Scheduled Ship Date    2020-08-26 00:00:00
Order Number                             6
Name: 5, dtype: object
Total LM Order QTY                  746269
Width                                  670
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             1
Name: 0, dtype: object
Total LM Order QTY                  980392
Width                                  510
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             2
Name: 1, dtype: object
Total LM Order QTY                  816327
Width                                  245
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             3
Name: 2, dtype: object
Total LM Order QTY             1.36364e+06
Width                                  440
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             4
Name: 3, dtype: object
Total LM Order QTY             1.33333e+06
Width                                  600
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             5
Name: 4, dtype: object
Total LM Order QTY             1.32159e+06
Width                                  454
Scheduled Ship Date    2020-08-26 00:00:00
Order Number                             6
Name: 5, dtype: object
Total LM Order QTY                  746269
Width                                  670
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             1
Name: 0, dtype: object
Total LM Order QTY                  980392
Width                                  510
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             2
Name: 1, dtype: object
Total LM Order QTY                  816327
Width                                  245
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             3
Name: 2, dtype: object
Total LM Order QTY             1.36364e+06
Width                                  440
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             4
Name: 3, dtype: object
Total LM Order QTY             1.33333e+06
Width                                  600
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             5
Name: 4, dtype: object
Total LM Order QTY             1.32159e+06
Width                                  454
Scheduled Ship Date    2020-08-26 00:00:00
Order Number                             6
Name: 5, dtype: object
Total LM Order QTY                  746269
Width                                  670
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             1
Name: 0, dtype: object
Total LM Order QTY                  980392
Width                                  510
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             2
Name: 1, dtype: object
Total LM Order QTY                  816327
Width                                  245
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             3
Name: 2, dtype: object
Total LM Order QTY             1.36364e+06
Width                                  440
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             4
Name: 3, dtype: object
Total LM Order QTY             1.33333e+06
Width                                  600
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             5
Name: 4, dtype: object
Total LM Order QTY             1.32159e+06
Width                                  454
Scheduled Ship Date    2020-08-26 00:00:00
Order Number                             6
Name: 5, dtype: object
Total LM Order QTY                  746269
Width                                  670
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             1
Name: 0, dtype: object
Total LM Order QTY                  980392
Width                                  510
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             2
Name: 1, dtype: object
Total LM Order QTY                  816327
Width                                  245
Scheduled Ship Date    2020-08-15 00:00:00
Order Number                             3
Name: 2, dtype: object
Total LM Order QTY             1.36364e+06
Width                                  440
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             4
Name: 3, dtype: object
Total LM Order QTY             1.33333e+06
Width                                  600
Scheduled Ship Date    2020-08-23 00:00:00
Order Number                             5
Name: 4, dtype: object
Total LM Order QTY             1.32159e+06
Width                                  454
Scheduled Ship Date    2020-08-26 00:00:00
Order Number                             6
Name: 5, dtype: object

KeyError: "None of [Index(['Total LM Order QTY', 'Width', 'Scheduled Ship Date', 'Order Number'], dtype='object')] are in the [columns]"

In [120]:
schedule_with_order_info

[245     NaN
 440     NaN
 454     NaN
 510     NaN
 600     NaN
 670     6.0
 freq    1.0
 Name: 0, dtype: float64, 245     1.0
 440     NaN
 454     NaN
 510     NaN
 600     4.0
 670     2.0
 freq    1.0
 Name: 1, dtype: float64, 245     NaN
 440     NaN
 454     NaN
 510     1.0
 600     6.0
 670     NaN
 freq    1.0
 Name: 2, dtype: float64, 245     NaN
 440     NaN
 454     NaN
 510     3.0
 600     4.0
 670     NaN
 freq    1.0
 Name: 3, dtype: float64, 245     NaN
 440     NaN
 454     2.0
 510     6.0
 600     NaN
 670     NaN
 freq    1.0
 Name: 4, dtype: float64, 245     NaN
 440     NaN
 454     9.0
 510     NaN
 600     NaN
 670     NaN
 freq    1.0
 Name: 5, dtype: float64, 245     NaN
 440     7.0
 454     2.0
 510     NaN
 600     NaN
 670     NaN
 freq    1.0
 Name: 6, dtype: float64, 245     4.0
 440     7.0
 454     NaN
 510     NaN
 600     NaN
 670     NaN
 freq    1.0
 Name: 7, dtype: float64, 245     4.0
 440     NaN
 454     NaN
 510     NaN
 600     NaN
 670     NaN
 freq    1.0
 Name: 8, dtype: float64]

In [30]:
extras

     0    1    2    3    4    5    6
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [27]:
master_knife = optimize_schedule(sol, widths, neckins, df_filtered, L, setup_df, 
                           speed_df, doffs_in_jumbo, start_date, 'Time (Knife Changes)')
deckle_time = master_knife.iloc[-1]['Completion Date'] - master_knife.iloc[0]['Completion Date']
print("deckle time, knife changes objective: {}".format(str(deckle_time).split('.')[0]))

../utils.py:490: FutureWarning:

Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

ValueError: Length mismatch: Expected axis has 7 elements, new values have 6 elements

In [44]:
master_late = optimize_schedule(sol, widths, neckins, df_filtered, L, setup_df, 
                           speed_df, doffs_in_jumbo, start_date, 'Late Orders')
deckle_time = master_late.iloc[-1]['Completion Date'] - master_late.iloc[0]['Completion Date']
print("deckle time, late orders objective: {}".format(str(deckle_time).split('.')[0]))

KeyError: '170'